server:
  port: 8082

spring:

  datasource:
    initialization-mode: never
    url: jdbc:postgresql://************/cipr
    username: postgres
    password: ***************

  jpa:
    generate-ddl: false

    hibernate:
      ddl-auto: none

    properties.hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect